### PR TITLE
[DEVHAS-94] Requeue the Component when its Application can't be found

### PR DESCRIPTION
**Pull request by johnmcollier**
Fixes https://issues.redhat.com/browse/DEVHAS-94

Updates the Component controller logic to requeue if a Component's Application cannot be found, or is not finished reconciling.

### CODE REVIEW

**Review by maysunfaisal — APPROVED** [review]

**Comment by maysunfaisal** [comment]
@johnmcollier do we want a simple test where we create a component before an application?

**Comment by johnmcollier** [comment]
@maysunfaisal I'll update the existing test case (#4) that covered this scenario

**Comment by johnmcollier** [comment]
@maysunfaisal Updated, thanks!

**Review by maysunfaisal — APPROVED** [review]

**Pull request merged**
