### PR TITLE
Update OWNERS file

### PR DESCRIPTION
**Pull request by maysunfaisal**
Update OWNERS file

### CODE REVIEW

**Comment by maysunfaisal** [comment]
@thepetk could you help review?

**Review by thepetk — APPROVED** [review]
/lgtm I'm not sure only if we need to add Jdubrick too here :thinking:

**Comment by maysunfaisal** [comment]
@thepetk I think for now we can keep it as ppl who have contributed to the repo

**Comment by thepetk** [comment]
> for

Sgtm

**Pull request merged**
