### PR TITLE
Update component spec with default image if the image is not set

### PR DESCRIPTION
**Pull request by mmorhun**
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>

This MR explicitly sets default component image in component spec if it was not set manually.
Such behavior:
- Makes it more clear for the user which image is used and how to change it.
- Analysis of the component (including gitops creation) is made from actual component configuration in the cluster, not a modified in-memory copy.

### CODE REVIEW

**Comment by Michkov** [comment]
Fix of [PLNSRVCE-291](https://issues.redhat.com/browse/PLNSRVCE-291)

**Review by Michkov — APPROVED** [review]

**Review by johnmcollier — APPROVED** [review]

**Pull request merged**
