### PR TITLE
[DEVHAS-266] Don't return context as part of local DockerfileURI

### PR DESCRIPTION
**Pull request by johnmcollier**
### What does this PR do?:
When we were returning local Dockerfile URIs in the status of CDQs, we were appending the context folder to the URI. Since the context is already returned separately as part of the CDQ result, this would result in an invalid Dockerfile path (e.g. frontend/frontend/Dockerfile).

This PR removes that, so that the context path is not appended to the Dockerfile URI.

Since a test case didn't exist that covered this, I've added one

### Which issue(s)/story(ies) does this PR fixes:
https://issues.redhat.com/browse/DEVHAS-266

### PR acceptance criteria:

- [x] Unit/Functional tests

  

- [ ] Documentation 

   

- [ ] Client Impact

### CODE REVIEW

**Comment by flacatus** [comment]
image (30)

Builded and tested but got an error in the pipeline.

```yaml
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    applicationFailCounter: '0'
    appstudio.openshift.io/component-initial-build: processed
    skip-initial-checks: 'true'
  resourceVersion: '33836'
  name: frontend-quality-dashboard-jern
  namespace: multi-comp-e2e-xvrn-tenant
  finalizers:
    - component.appstudio.redhat.com/finalizer
spec:
  application: multi-component-application
  componentName: frontend-quality-dashboard-jern
  containerImage: >-
    quay.io/redhat-appstudio-qe/test-images-protected:mvAp7-frontend-quality-dashboard-jern
  resources: {}
  secret: e2e-github-secret
  source:
    git:
      context: frontend
      dockerfileUrl: Dockerfile
      url: 'https://github.com/redhat-appstudio/quality-dashboard.git'
```

**Comment by Michkov** [comment]
@flacatus are you testing manually? What are the paramerers of pipelinerun?

**Comment by Michkov** [comment]
Build-service is using `Component.spec.source.git.context + Component.status.devfile.components[x].image.dockerfile.buildContext` to compose final context for pipelinerun. We are expecting that generated `.status.devfile` is related to `Component.spec.source.git.context`. 

https://redhat-internal.slack.com/archives/C02HZRGKDEY/p1675242002586259

**Comment by johnmcollier** [comment]
@Michkov I think we uncovered another bug in HAS.

Per https://redhat-internal.slack.com/archives/C02HZRGKDEY/p1675242002586259, the buildContext in the devfile is relative to the folder that contains the devfile. For Components that don’t have a devfile, this would be the component’s root folder (e.g. frontend/)

HAS is setting the devfile's buildContext for Dockerfile components to be the git context that gets passed (e.g. frontend/). But since the buildcontext is supposed to be relative to the Component, we shouldn’t be setting it to the Git context in this case.

**Review by flacatus — APPROVED** [review]

**Pull request merged**
