### PR TITLE
chore: Update Grafana dashboard path

### PR DESCRIPTION
**Pull request by avi-biton**
### What does this PR do?:
Update Grafana dashboard path after change in `infra-deployments`

### CODE REVIEW

**Comment by avi-biton** [comment]
@maysunfaisal @yangcao77 can you please review?

**Review by maysunfaisal — APPROVED** [review]

**Comment by maysunfaisal** [comment]
FYI to PR readers: https://github.com/redhat-appstudio/infra-deployments/pull/2169

**Comment by avi-biton** [comment]
@kim-tsao Can you please review?

**Comment by maysunfaisal** [comment]
@avi-biton can you pls rebase and push again? The new commit should fix the test failure we are seeing on Pact tests

**Comment by avi-biton** [comment]
Rebased

**Pull request merged**
