### PR TITLE
[Devtools Week] Rename RHTAP occurrences to Konflux

### PR DESCRIPTION
**Pull request by michael-valdron**
### What does this PR do?:

Changes occurrences of RHTAP to current name Konflux in source and documentation.

### PR acceptance criteria:

- [ ] Unit/Functional tests

  

- [X] Documentation 

   

- [ ] Client Impact

### CODE REVIEW

**Comment by michael-valdron** [comment]
> @michael-valdron Looks good to me. A quick question is if you think is ok to update these [dockerfile labels](https://github.com/redhat-appstudio/application-service/blob/main/Dockerfile#L57-L61):
> 
>     * `description`
> 
>     * `io.k8s.description`
> 
>     * `summary`

@thepetk Oops good catch I'll revise these as well.

**Comment by maysunfaisal** [comment]
@michael-valdron  I would check what the other teams Dockerfile labels look like if they have one

**Comment by michael-valdron** [comment]
> @michael-valdron I would check what the other teams Dockerfile labels look like if they have one

From what I can see we are the first to undergo the renaming to Konflux, to this extent a least. Other components still use RHTAP in their labels. The label I am most concerned with keeping consistent with other teams is `io.openshift.tags` to keep HAS grouped with other components.

Some that I found still use the `rhtap` tag for their images:
- [integration-service](https://github.com/redhat-appstudio/integration-service/blob/e009d17c082c324265322656bf1d36d7dbf58d14/Dockerfile#L46)
- [build-service](https://github.com/redhat-appstudio/build-service/blob/29b09e5d8350f75c92d5796fbbf62647fe28610b/Dockerfile#L32)

Others don't specify any tags:
- [release-service](https://github.com/redhat-appstudio/release-service/blob/a9e97634a8639a4296fbd1b52fc0cd8dbbfda2f6/Dockerfile)
- [jvm-build-service](https://github.com/redhat-appstudio/jvm-build-service/blob/b9bb9d4e19d3b361d402091116e85c994f0eb5c6/Dockerfile)
- [results-service](https://github.com/redhat-appstudio/results-service/blob/34f9f002a997e1e701ff155aa120bd2b48fefa5d/Dockerfile)

@maysunfaisal Based on these findings should we just revert `io.openshift.tags` to `rhtap` and keep the renaming in the descriptor fields? Or maybe we exclude our `Dockerfile` from these changes at the time?

**Comment by maysunfaisal** [comment]
@michael-valdron lets bring this up in the standup tomorrow. I dont think it should matter.

**Comment by michael-valdron** [comment]
> @maysunfaisal Based on these findings should we just revert `io.openshift.tags` to `rhtap` and keep the renaming in the descriptor fields? Or maybe we exclude our `Dockerfile` from these changes at the time?

During team discussion on this, we decided to revert back to `rhtap` for all `Dockerfile` labels to avoid bundling and metric issues.

**Pull request closed without merging**
