### PR TITLE
Add build gitops generation

### PR DESCRIPTION
**Pull request by mmorhun**
Reimplementation of https://github.com/redhat-appstudio/application-service/pull/42 using single commit
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>

### CODE REVIEW

**Comment by mmorhun** [comment]
@elsony @johnmcollier @maysunfaisal please take a look

**Comment by sbose78** [comment]
@mmorhun  
As a best practice, let's have someone in the Build team take a look first :) That'll make life slightly easier for the HAS team.

**Review by johnmcollier — COMMENTED** [review]
I pulled down your changes and created a Component, which gave me https://github.com/redhat-appstudio-appdata/petclinic-application-service-burn-relief

I tried using `kustomize build components/component-sample-feb9/base | oc apply -f -` to see what happens, and I got the following error:
```
johncollier@jcollier-mac petclinic-application-service-burn-relief % kustomize build components/component-sample-feb9/base | oc apply -f -
service/component-sample-feb9 configured
deployment.apps/component-sample-feb9 configured
route.route.openshift.io/elcomponent-sample-feb9 configured
persistentvolumeclaim/appstudio configured
route.route.openshift.io/component-sample-feb9 configured
unable to recognize "STDIN": no matches for kind "EventListener" in version "triggers.tekton.dev/v1beta1"
unable to recognize "STDIN": no matches for kind "TriggerTemplate" in version "triggers.tekton.dev/v1beta1"
```

It looks like the EventListener and TriggerTemplate resources created by HAS (at least on my cluster) are in the `triggers.tekton.dev/v1alpha1` API group/version, and there is no `triggers.tekton.dev/v1beta1` API group/version on my cluster.

Should we be specifiying `triggers.tekton.dev/v1alpha` instead?

**Review by maysunfaisal — COMMENTED** [review]
Other than the recommendations John suggested, I have nothing to add. Looks good on my end, was able to test the PR without any issues.

**Comment by mmorhun** [comment]
@johnmcollier we decided to update API versions from `v1alpha1` to `v1beta1` in `infra-deployments`.
This PR makes sure that resources generated under `.tekton` directory and created directly have the same spec as the same build/generate functions are used.

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
Tested merge request - works fine.

**Review by johnmcollier — APPROVED** [review]

**Pull request merged**
