### PR TITLE
Use the Component revision

### PR DESCRIPTION
**Pull request by jduimovich**
This PR contains a fix for Components where the default branch is other than `main` and is specified in the the Component Spec as part of the source git reference

The repository https://github.com/Apicurio/apicurio-registry uses `master` instead of main but the reference in the component is ignored when a build is created and the build fails. This PR adds a check to setthe revision into the pipeline run if it is set in the component. 

Example (note the `revision: master`) 
```
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: service-registry
spec:
  componentName: service-registry
  application: service-registry
  containerImage: quay.io/jduimovich0/service-registry
  source:
    git:
      url: https://github.com/Apicurio/apicurio-registry
      revision: master
      devfileUrl: https://raw.githubusercontent.com/jduimovich/appstudio-e2e-demos/main/demos/service-registry/devfiles/devfile.yaml
  build:
    containerImage: quay.io/jduimovich0/service-registry:1
```
 
 The application definition for the above component.  It will fail to build as the default will checkout `main`, instead of `master`. 
```
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: service-registry 
spec:
  description: "service-registry built in App Studio"
  displayName: service-registry
```

To test, rebuild both application-service and build-service as the code is shared in both and create a Component using the above as an example build.

### CODE REVIEW

**Comment by gabemontero** [comment]
a hacbs / jvm build service need for sure, given our long term goal of building service registry end to end from appstudio invoking jvm build service via creation of a component

thanks @jduimovich 

@sbose78 @Michkov @stuartwdouglas (for when they return from PTO)

**Review by gabemontero — COMMENTED** [review]
you have time to write a unit test @jduimovich or shall @mmorhun or myself add one after this gets merged ?

**Review by johnmcollier — COMMENTED** [review]
Can you add a test case to [TestGetParamsForComponentBuild](https://github.com/redhat-appstudio/application-service/blob/99bd9270ab7a72b7ff73c5d745b06943bc6d0690/gitops/generate_build_test.go#L652) where the Git Source revision is set to something?

**Comment by jduimovich** [comment]
I added a test case for the revision param use case as well and fixing the formatting (extra spaces)

**Comment by gabemontero** [comment]
thanks @jduimovich 

the `kcp` submodule you added appears to be causing problems with the image build:

`{"command":"PWD=/go/src/github.com/redhat-appstudio/application-service  git submodule update --init --recursive","component":"clonerefs","error":"exit status 1","file":"k8s.io/test-infra/prow/pod-utils/clone/clone.go:83","func":"k8s.io/test-infra/prow/pod-utils/clone.Run.func2","level":"info","msg":"Ran command","output":"No submodule mapping found in .gitmodules for path 'kcp'\n","severity":"info","time":"2022-07-07T03:30:28Z"}`

maybe try to take that on in a separate PR (unless the resolution here is obvious to you) ?

**Comment by jduimovich** [comment]
@gabemontero  --- yes, adding kcp was an accident, when the `make test`  failed it prints the instruction to build kcp. I thought I had checked the commits and had removed it pre-pr

**Comment by gabemontero** [comment]
/lgtm

/assign @johnmcollier 

I think we are good to go - just need the approve label from @johnmcollier

**Pull request merged**
