### PR TITLE
Delete isHACBS flag

### PR DESCRIPTION
**Pull request by mmorhun**
### What does this PR do?:
Delete HACBS flag as AppStudio and HACBS are merged.

### Which issue(s)/story(ies) does this PR fixes:
[PLNSRVCE-992](https://issues.redhat.com/browse/PLNSRVCE-992)

### PR acceptance criteria:

- [x] Unit/Functional tests
- [ ] Documentation 
- [ ] Client Impact

### CODE REVIEW

**Review by johnmcollier — APPROVED** [review]

**Comment by johnmcollier** [comment]
@mmorhun Can you rebase?

**Comment by mmorhun** [comment]
@johnmcollier, thank you, done.

**Review by tkdchen — APPROVED** [review]
Nice!

**Pull request merged**
