### PR TITLE
Update pact to v2 to support v3 schema

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
Update pact-go to v2 to have support for v3 schema and new matchers. Remove the chains and now the synchronization issue is not present.

### Which issue(s)/story(ies) does this PR fixes:
https://issues.redhat.com/browse/HAC-4597

Related PR on the HAC-dev side: https://github.com/openshift/hac-dev/pull/774

### CODE REVIEW

**Review by maysunfaisal — APPROVED** [review]

**Comment by Katka92** [comment]
It's currently failing on a missing library. I'll take a look at that.

**Comment by maysunfaisal** [comment]
@flacatus this PR ok with you? we can lgtm it if everything's good.

**Pull request merged**
