### PR TITLE
[DEVHAS-611] Update Component create metrics for better data

### PR DESCRIPTION
**Pull request by maysunfaisal**
### What does this PR do?:

- Updates the component metrics only if the current state is different than the prev state, this helps avoid spamming metrics due to HAS controller retry logic
- Wrapper function for Component create metrics (other metrics left untouched, outside the scope of PR), whose job is to compare previous error and current error and update metrics accordingly
- Remove metrics tracking from Gitops logic due to future commitments
- Rearrange metrics dir to individual files (cut-paste) 

### Which issue(s)/story(ies) does this PR fixes:

https://issues.redhat.com/browse/DEVHAS-611

### PR acceptance criteria:

- [x] Unit/Functional tests

  

- [ ] Documentation 

   

- [ ] Client Impact

  

### How to test changes / Special notes to the reviewer:
tests should pass

### CODE REVIEW

**Review by michael-valdron — COMMENTED** [review]
Changes looks good to me.

I saw e2e tests did not fail under a recent PR, https://github.com/redhat-appstudio/application-service/pull/442, seeing if retest does not reproduce `error: the path "deploy/member-operator/appstudio-dev/" does not exist`.

**Comment by michael-valdron** [comment]
@maysunfaisal Rebasing on your recent changes might fix https://github.com/redhat-appstudio/application-service/actions/runs/7791255552/job/21327116796?pr=441, but I also noticed your comment about the linter fix: https://github.com/redhat-appstudio/application-service/pull/442#issuecomment-1932256932

**Comment by michael-valdron** [comment]
/retest

Failures this time look like flaky ones, retrying.

**Comment by maysunfaisal** [comment]
@michael-valdron I merged https://github.com/redhat-appstudio/application-service/pull/442 which should address the kube linter error and rebased this PR. 

The tekton pipeline is broken because we dont promote commits to infra-deploy automatically anymore. I think John will/may be setting that up with their EPIC later. Until then we have to promote it manually.

**Comment by maysunfaisal** [comment]
@michael-valdron This PR can be lgtm'd.

I confirmed that the tekton pipeline we are looking for a success is `application-service-on-pull-request` which is passing, the pipeline `has-on-pull-request` is outdated and there is a PR to remove it https://github.com/redhat-appstudio/application-service/pull/438. 

The outdated tekton builds are now replaced by konflux builds and the `application-service-on-pull-request` pipeline runs on Konflux:

Screenshot 2024-02-07 at 3 36 15 PM

(Confirmed on older PRs and my direct conversation with John)

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Pull request merged**
