### PR TITLE
chore(DEVHAS-657): Update application-api references

### PR DESCRIPTION
**Pull request by thepetk**
### What does this PR do?:

This PR updates all references to the `application-api` using the new organization (`konflux-ci`) 

### Which issue(s)/story(ies) does this PR fixes:
https://issues.redhat.com/browse/DEVHAS-657

### PR acceptance criteria:

- [ ] Unit/Functional tests

  

- [ ] Documentation 

   

- [ ] Client Impact

### CODE REVIEW

**Comment by michael-valdron** [comment]
FYI changes here may conflict with #480, I'd recommend merging #480 first.

**Review by johnmcollier — APPROVED** [review]

**Pull request merged**
