### PR TITLE
Update controller-gen version

### PR DESCRIPTION
**Pull request by maysunfaisal**
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>

I updated my personal go to 1.19:
```
$ go version
go version go1.19 darwin/amd64
```

but it seems like controller-gen was having some issues with the latest go:
```
$ make generate
/Users/maysun/dev/appstudio/application-service/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/usr/local/go/src/sync/atomic/type.go:39:16: expected ']', found any
/usr/local/go/src/sync/atomic/type.go:39:19: expected ';', found ']'
/usr/local/go/src/sync/atomic/type.go:39:19: expected type, found ']'
/usr/local/go/src/sync/atomic/type.go:45:34: expected declaration, found 'return'
/usr/local/go/src/sync/atomic/type.go:39:16: expected ']', found any
/usr/local/go/src/sync/atomic/type.go:39:19: expected ';', found ']'
/usr/local/go/src/sync/atomic/type.go:39:19: expected type, found ']'
/usr/local/go/src/sync/atomic/type.go:45:34: expected declaration, found 'return'
/usr/local/go/src/sync/atomic/type.go:39:16: expected ']', found any
/usr/local/go/src/sync/atomic/type.go:39:19: expected ';', found ']'
/usr/local/go/src/sync/atomic/type.go:39:19: expected type, found ']'
/usr/local/go/src/sync/atomic/type.go:45:34: expected declaration, found 'return'
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make: *** [generate] Error 1
```

Updated controller-gen to latest as per https://github.com/kubernetes-sigs/controller-tools/releases

Seems fine now:
```
$ go version
go version go1.19 darwin/amd64
$ ./bin/controller-gen --version
Version: v0.9.2
$ make generate
/Users/maysun/dev/appstudio/application-service/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
$ echo $?
0
```

### CODE REVIEW

**Review by johnmcollier — APPROVED** [review]

**Comment by johnmcollier** [comment]
```
generators

+webhook                                                                                                                                           package  generates (partial) {Mutating,Validating}WebhookConfiguration objects.                        
+schemapatch[:generateEmbeddedObjectMeta=<bool>],manifests=<string>[,maxDescLen=<int>]                                                             package  patches existing CRDs with new schemata.                                                      
+rbac:roleName=<string>                                                                                                                            package  generates ClusterRole objects.                                                                
+object[:headerFile=<string>][,year=<string>]                                                                                                      package  generates code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.  
+crd[:allowDangerousTypes=<bool>][,crdVersions=<[]string>][,generateEmbeddedObjectMeta=<bool>][,ignoreUnexportedFields=<bool>][,maxDescLen=<int>]  package  generates CustomResourceDefinition objects.                                                   


generic

+paths=<[]string>  package  represents paths and go-style path patterns to use as package roots.  


output rules (optionally as output:<generator>:...)

+output:artifacts[:code=<string>],config=<string>  package  outputs artifacts to different locations, depending on whether they're package-associated or not.   
+output:dir=<string>                               package  outputs each artifact to the given directory, regardless of if it's package-associated or not.      
+output:none                                       package  skips outputting anything.                                                                          
+output:stdout                                     package  outputs everything to standard-out, with no separation.                                             

run `controller-gen crd:trivialVersions=true,preserveUnknownFields=false rbac:roleName=manager-role webhook paths=./... output:crd:artifacts:config=config/crd/bases -w` to see all available markers, or `controller-gen crd:trivialVersions=true,preserveUnknownFields=false rbac:roleName=manager-role webhook paths=./... output:crd:artifacts:config=config/crd/bases -h` for usage
make: *** [Makefile:88: manifests] Error 1
Error: Process completed with exit code 2.
```

@maysunfaisal You might need to update the workflow to Go 1.19.

**Comment by maysunfaisal** [comment]
@johnmcollier yep `manifests` is erroring out because the controller-gen CLI is not backward compatible with some of the options, checking right now

**Comment by johnmcollier** [comment]
[SPI's operator is on controller-gen v0.9.2](https://github.com/redhat-appstudio/service-provider-integration-operator/blob/main/Makefile#L270), might be worthwhile looking at their makefile to see what you need to change.

**Comment by maysunfaisal** [comment]
@johnmcollier we're losing a few of teh flags to remain backwards compatible with the old Kube like trivialVersions. 

Screen Shot 2022-08-30 at 2 58 39 PM


Removing those options and just using  `crd` like SPI looks fine but errors out on kcp manifests. What am i looking at?
```
$ hack/generate-kcp-api.sh 
/Users/maysun/go/bin/kubectl-kcp
error: no kind "MutatingWebhookConfiguration" is registered for version "admissionregistration.k8s.io/v1" in scheme "k8s.io/apimachinery@v0.0.0-20220721163516-e48c0ebdf7b8/pkg/runtime/scheme.go:100"
```

it seems to be erroring out on 
```
for CRD in $( ls ${CRD_DIR} ); do
  kubectl-kcp crd snapshot -f "${CRD_DIR}/${CRD}" --prefix v${PREFIX} >> ${KCP_API_SCHEMA_FILE_NEW}
done
```

**Comment by johnmcollier** [comment]
generate-kcp-api.sh is copied from SPI (https://github.com/redhat-appstudio/service-provider-integration-operator/blob/main/hack/generate-kcp-api.sh) so wonder if there's something we need to update there?

**Comment by maysunfaisal** [comment]
@johnmcollier nope its pretty much the same

**Pull request closed without merging**
